### ISSUE TITLE
Command not found : bc line 17

### ISSUE THREAD

**Issue by maxking** [dmukhg/utility#1]
After installing the script when i run it it my terminal it says

`./eye-notify: line 17: bc: command not found. Cannot parse the integer value for ' ' for --expiry-time`

**Comment by dmukhg** [comment]
Please try running the bc command directly.  On a prompt, type bc.  From the error message, I figure that you don't have it installed.  If that infact is the problem, apt-get install bc should resolve the issue.

**Comment by dmukhg** [comment]
[bc](http://www.gnu.org/s/bc/) is the command line arbitrary precision calculator from GNU.  I use it to convert minutes to seconds.
